# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.CharField(default=datetime.datetime(2016, 8, 7, 17, 53, 42, 247977, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
